/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package net.xabc.oo.hr.web.action;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.xabc.oo.hr.biz.DataDetaiBiz;
import net.xabc.oo.hr.biz.RightsBiz;
import net.xabc.oo.hr.common.SelectOptions;
import net.xabc.oo.hr.utils.date.DateFormat;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

/** 
 * MyEclipse Struts
 * Creation date: 12-10-2009
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class OptionsAction extends DispatchAction {
	/*
	 * Generated Methods
	 */
	 private RightsBiz rightsBiz;
	 private SelectOptions selectOptions;
	 private DataDetaiBiz dataDetailBiz;

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward getOptions(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String forward="";
		try {
			String branchString=selectOptions.getBranchString().toString();
			String nationString=selectOptions.getDataDetailsByDataTypeId(1).toString();
			String degreeString=selectOptions.getDataDetailsByDataTypeId(2).toString();
			String polityString=selectOptions.getDataDetailsByDataTypeId(3).toString();
			if(branchString!=null){
				request.setAttribute("branchString", branchString);
				request.setAttribute("nationString", nationString);
				request.setAttribute("degreeString",degreeString);
				request.setAttribute("polityString",polityString);
			}
			forward="addDossier";
		} catch (RuntimeException e) {
			e.printStackTrace();
		}
		
		return mapping.findForward(forward);
	}
	
	
	/**
	 * 获取所有的部门列表
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 */
	public ActionForward getBranch(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String forward="";
		String dir=request.getParameter("forward");
		try {
			String branchString=selectOptions.getBranchString().toString();
			String roleString=selectOptions.getRoleString().toString();
			List rightsList=rightsBiz.selectAllNodes();
			String date=DateFormat.getDate();
			List rightsChildNodes=rightsBiz.selectAllChildNodes();
			if(branchString!=null && roleString!=null){
				request.setAttribute("branchString", branchString);
				request.setAttribute("roleString", roleString);
				request.setAttribute("rightsNode", rightsList);
				request.setAttribute("rightsChildNodes", rightsChildNodes);
			}
			request.setAttribute("date", date);
			forward=dir;
		} catch (RuntimeException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return mapping.findForward(forward);
	}
	
	/**
	 * 查找所有的试题分类
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 */
	public ActionForward selectLevel(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String forward="";
		String dataDetailId=request.getParameter("dataDetailId");
		try {
			String levelString=selectOptions.getDataDetailsByDataTypeId(4).toString();
			 request.setAttribute("levelString", levelString);
			 request.setAttribute("dataDetailId", dataDetailId);
			forward="addSecond";
		} catch (RuntimeException e) {
			e.printStackTrace();
		}
		return mapping.findForward(forward);
	}

	public SelectOptions getSelectOptions() {
		return selectOptions;
	}

	public void setSelectOptions(SelectOptions selectOptions) {
		this.selectOptions = selectOptions;
	}


	public DataDetaiBiz getDataDetailBiz() {
		return dataDetailBiz;
	}


	public void setDataDetailBiz(DataDetaiBiz dataDetailBiz) {
		this.dataDetailBiz = dataDetailBiz;
	}


	public RightsBiz getRightsBiz() {
		return rightsBiz;
	}


	public void setRightsBiz(RightsBiz rightsBiz) {
		this.rightsBiz = rightsBiz;
	}

	 
}