/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package net.xabc.oo.hr.web.action;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import net.xabc.oo.hr.web.form.UploadForm;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

/** 
 * MyEclipse Struts
 * Creation date: 12-10-2009
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class UploadAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String forward="";
		UploadForm uForm=(UploadForm)form;
		FormFile file=uForm.getMyFile();
		if(file!=null){
			String dir=request.getSession(true).getServletContext().getRealPath("/upload");
			OutputStream fos=null;
			try {
				fos=new FileOutputStream(dir+"/"+file.getFileName());
				fos.write(file.getFileData(),0,file.getFileSize());
				fos.flush();
				request.setAttribute("picturePath",dir+"/"+file.getFileName());
				forward="addDossier";
			} catch (FileNotFoundException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} finally{
				try {
					fos.close();
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		}
      return mapping.findForward(forward);
   	}
	}
		 