/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package net.xabc.oo.hr.web.form;

import java.util.Date;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/**
 * MyEclipse Struts Creation date: 12-22-2009
 * 
 * XDoclet definition:
 * 
 * @struts.form name="EmplloyForm"
 */
public class EmployForm extends ActionForm {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/*
	 * Generated Methods
	 */
	private Integer resumeId;

	private String personName;

	private Date resumeTime;

	private String resumeSex;

	private Integer resumeAge;

	private Date resumeBirthday;

	private Integer resumeDegree;
	
	private Integer resumePositionId;

	private String resumeGraduate;

	private Integer resumePolity;

	private String resumePhoto;

	private String resumeIdCard;

	private Integer resumeNation;

	private String resumeSpeciality;

	private String resumeHistory;

	private String resumeBirthPlace;

	private String resumeRequire;

	private String resumePhone;

	private String resumePostcode;

	private String resumeEmail;

	private String resumeFamilyPhone;

	private String resumeHobby;

	private String resumeSkill;

	private Integer resumeInterviewstatus;

	private Integer resumeStatus;

	private String resumeRegister;

	private String resumeRegisterTime;

	private String resumeChecker;

	private String resumeCheckTime;

	private Integer resumeCheckStatus;

	private String resumeCheckCommit;
	
	
	private Integer eiId;

	private String eiName;

	private Integer positionId;

	private Integer eiGrade;

	private String eiFace;

	private String eiAbility;

	private String eiInterviewer;

	private String eiInterviewTime;

	private String eiChecker;

	private String eiCheckTime;

	private String eiResult;

	private String eiComment;

	private Integer eiInterviewStatus;

	private Integer eiCheckStatus;

	public String getEiAbility() {
		return eiAbility;
	}
	public void setEiAbility(String eiAbility) {
		this.eiAbility = eiAbility;
	}
	public String getEiChecker() {
		return eiChecker;
	}
	public void setEiChecker(String eiChecker) {
		this.eiChecker = eiChecker;
	}
	public Integer getEiCheckStatus() {
		return eiCheckStatus;
	}
	public void setEiCheckStatus(Integer eiCheckStatus) {
		this.eiCheckStatus = eiCheckStatus;
	}
	public String getEiCheckTime() {
		return eiCheckTime;
	}
	public void setEiCheckTime(String eiCheckTime) {
		this.eiCheckTime = eiCheckTime;
	}
	public String getEiComment() {
		return eiComment;
	}
	public void setEiComment(String eiComment) {
		this.eiComment = eiComment;
	}
	public String getEiFace() {
		return eiFace;
	}
	public void setEiFace(String eiFace) {
		this.eiFace = eiFace;
	}
	public Integer getEiGrade() {
		return eiGrade;
	}
	public void setEiGrade(Integer eiGrade) {
		this.eiGrade = eiGrade;
	}
	public Integer getEiId() {
		return eiId;
	}
	public void setEiId(Integer eiId) {
		this.eiId = eiId;
	}
	public String getEiInterviewer() {
		return eiInterviewer;
	}
	public void setEiInterviewer(String eiInterviewer) {
		this.eiInterviewer = eiInterviewer;
	}
	public Integer getEiInterviewStatus() {
		return eiInterviewStatus;
	}
	public void setEiInterviewStatus(Integer eiInterviewStatus) {
		this.eiInterviewStatus = eiInterviewStatus;
	}
	public String getEiInterviewTime() {
		return eiInterviewTime;
	}
	public void setEiInterviewTime(String eiInterviewTime) {
		this.eiInterviewTime = eiInterviewTime;
	}
	public String getEiName() {
		return eiName;
	}
	public void setEiName(String eiName) {
		this.eiName = eiName;
	}
	public String getEiResult() {
		return eiResult;
	}
	public void setEiResult(String eiResult) {
		this.eiResult = eiResult;
	}
	public String getPersonName() {
		return personName;
	}
	public void setPersonName(String personName) {
		this.personName = personName;
	}
	public Integer getPositionId() {
		return positionId;
	}
	public void setPositionId(Integer positionId) {
		this.positionId = positionId;
	}
	public Integer getResumeAge() {
		return resumeAge;
	}
	public void setResumeAge(Integer resumeAge) {
		this.resumeAge = resumeAge;
	}
	public Date getResumeBirthday() {
		return resumeBirthday;
	}
	public void setResumeBirthday(Date resumeBirthday) {
		this.resumeBirthday = resumeBirthday;
	}
	public String getResumeBirthPlace() {
		return resumeBirthPlace;
	}
	public void setResumeBirthPlace(String resumeBirthPlace) {
		this.resumeBirthPlace = resumeBirthPlace;
	}
	public String getResumeCheckCommit() {
		return resumeCheckCommit;
	}
	public void setResumeCheckCommit(String resumeCheckCommit) {
		this.resumeCheckCommit = resumeCheckCommit;
	}
	public String getResumeChecker() {
		return resumeChecker;
	}
	public void setResumeChecker(String resumeChecker) {
		this.resumeChecker = resumeChecker;
	}
	public Integer getResumeCheckStatus() {
		return resumeCheckStatus;
	}
	public void setResumeCheckStatus(Integer resumeCheckStatus) {
		this.resumeCheckStatus = resumeCheckStatus;
	}
	public String getResumeCheckTime() {
		return resumeCheckTime;
	}
	public void setResumeCheckTime(String resumeCheckTime) {
		this.resumeCheckTime = resumeCheckTime;
	}
	public Integer getResumeDegree() {
		return resumeDegree;
	}
	public void setResumeDegree(Integer resumeDegree) {
		this.resumeDegree = resumeDegree;
	}
	public String getResumeEmail() {
		return resumeEmail;
	}
	public void setResumeEmail(String resumeEmail) {
		this.resumeEmail = resumeEmail;
	}
	public String getResumeFamilyPhone() {
		return resumeFamilyPhone;
	}
	public void setResumeFamilyPhone(String resumeFamilyPhone) {
		this.resumeFamilyPhone = resumeFamilyPhone;
	}
	public String getResumeGraduate() {
		return resumeGraduate;
	}
	public void setResumeGraduate(String resumeGraduate) {
		this.resumeGraduate = resumeGraduate;
	}
	public String getResumeHistory() {
		return resumeHistory;
	}
	public void setResumeHistory(String resumeHistory) {
		this.resumeHistory = resumeHistory;
	}
	public String getResumeHobby() {
		return resumeHobby;
	}
	public void setResumeHobby(String resumeHobby) {
		this.resumeHobby = resumeHobby;
	}
	public Integer getResumeId() {
		return resumeId;
	}
	public void setResumeId(Integer resumeId) {
		this.resumeId = resumeId;
	}
	public String getResumeIdCard() {
		return resumeIdCard;
	}
	public void setResumeIdCard(String resumeIdCard) {
		this.resumeIdCard = resumeIdCard;
	}
	public Integer getResumeInterviewstatus() {
		return resumeInterviewstatus;
	}
	public void setResumeInterviewstatus(Integer resumeInterviewstatus) {
		this.resumeInterviewstatus = resumeInterviewstatus;
	}
	public Integer getResumeNation() {
		return resumeNation;
	}
	public void setResumeNation(Integer resumeNation) {
		this.resumeNation = resumeNation;
	}
	public String getResumePhone() {
		return resumePhone;
	}
	public void setResumePhone(String resumePhone) {
		this.resumePhone = resumePhone;
	}
	public String getResumePhoto() {
		return resumePhoto;
	}
	public void setResumePhoto(String resumePhoto) {
		this.resumePhoto = resumePhoto;
	}
	public Integer getResumePositionId() {
		return resumePositionId;
	}
	public void setResumePositionId(Integer resumePositionId) {
		this.resumePositionId = resumePositionId;
	}
	public Integer getResumePolity() {
		return resumePolity;
	}
	public void setResumePolity(Integer resumePolity) {
		this.resumePolity = resumePolity;
	}
	public String getResumePostcode() {
		return resumePostcode;
	}
	public void setResumePostcode(String resumePostcode) {
		this.resumePostcode = resumePostcode;
	}
	public String getResumeRegister() {
		return resumeRegister;
	}
	public void setResumeRegister(String resumeRegister) {
		this.resumeRegister = resumeRegister;
	}
	public String getResumeRegisterTime() {
		return resumeRegisterTime;
	}
	public void setResumeRegisterTime(String resumeRegisterTime) {
		this.resumeRegisterTime = resumeRegisterTime;
	}
	public String getResumeRequire() {
		return resumeRequire;
	}
	public void setResumeRequire(String resumeRequire) {
		this.resumeRequire = resumeRequire;
	}
	public String getResumeSex() {
		return resumeSex;
	}
	public void setResumeSex(String resumeSex) {
		this.resumeSex = resumeSex;
	}
	public String getResumeSkill() {
		return resumeSkill;
	}
	public void setResumeSkill(String resumeSkill) {
		this.resumeSkill = resumeSkill;
	}
	public String getResumeSpeciality() {
		return resumeSpeciality;
	}
	public void setResumeSpeciality(String resumeSpeciality) {
		this.resumeSpeciality = resumeSpeciality;
	}
	public Integer getResumeStatus() {
		return resumeStatus;
	}
	public void setResumeStatus(Integer resumeStatus) {
		this.resumeStatus = resumeStatus;
	}
	public Date getResumeTime() {
		return resumeTime;
	}
	public void setResumeTime(Date resumeTime) {
		this.resumeTime = resumeTime;
	}
	/**
	 * Method validate
	 * 
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		return null;
	}
	/**
	 * Method reset
	 * 
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
	}

	
	
}