package net.xabc.oo.hr.entity;

import java.util.HashSet;
import java.util.Set;

/**
 * Branch generated by MyEclipse Persistence Tools
 */

public class Branch implements java.io.Serializable {

	// Fields

	private Integer branchId;

	private String branchName;

	private Set postions = new HashSet(0);

	private Set examsubjects = new HashSet(0);

	// Constructors

	/** default constructor */
	public Branch() {
	}

	/** minimal constructor */
	public Branch(String branchName) {
		this.branchName = branchName;
	}

	/** full constructor */
	public Branch(String branchName, Set postions, Set examsubjects) {
		this.branchName = branchName;
		this.postions = postions;
		this.examsubjects = examsubjects;
	}

	// Property accessors

	public Integer getBranchId() {
		return this.branchId;
	}

	public void setBranchId(Integer branchId) {
		this.branchId = branchId;
	}

	public String getBranchName() {
		return this.branchName;
	}

	public void setBranchName(String branchName) {
		this.branchName = branchName;
	}

	public Set getPostions() {
		return this.postions;
	}

	public void setPostions(Set postions) {
		this.postions = postions;
	}

	public Set getExamsubjects() {
		return this.examsubjects;
	}

	public void setExamsubjects(Set examsubjects) {
		this.examsubjects = examsubjects;
	}

}