package net.xabc.oo.hr.entity;

/**
 * Datadetail generated by MyEclipse Persistence Tools
 */

public class Datadetail implements java.io.Serializable {

	// Fields

	private Integer dataDetailId;

	private Datatype datatype;

	private String dataDetailName;

	// Constructors

	/** default constructor */
	public Datadetail() {
	}

	/** full constructor */
	public Datadetail(Datatype datatype, String dataDetailName) {
		this.datatype = datatype;
		this.dataDetailName = dataDetailName;
	}

	// Property accessors

	public Integer getDataDetailId() {
		return this.dataDetailId;
	}

	public void setDataDetailId(Integer dataDetailId) {
		this.dataDetailId = dataDetailId;
	}

	public Datatype getDatatype() {
		return this.datatype;
	}

	public void setDatatype(Datatype datatype) {
		this.datatype = datatype;
	}

	public String getDataDetailName() {
		return this.dataDetailName;
	}

	public void setDataDetailName(String dataDetailName) {
		this.dataDetailName = dataDetailName;
	}

}