package net.xabc.oo.hr.entity;

import java.util.Date;

/**
 * Employeelog generated by MyEclipse Persistence Tools
 */

public class Employeelog implements java.io.Serializable {

	// Fields

	private Integer elId;

	private Postion postion;

	private Integer elEmployeeId;

	private String elName;

	private Integer elAge;

	private String elSex;

	private Date elBirthday;

	private Integer elNation;

	private String elPhoto;

	private Integer elDegree;

	private String elEmail;

	private String elSpecially;

	private Integer elPolity;

	private String elFamilyAddress;

	private String elFamilyPhone;

	private Date elEntertime;

	private String elPhone;

	private String elMobile;

	private String elAddress;

	private String elQq;

	private String elPostcode;

	private String elHobby;

	private String elSkills;

	private String elRemart;

	private String elRegister;

	private Date elRegisterTime;

	private String elChecker;

	private Date elCheckTime;

	private Integer elCheckStatus;

	private Date elChangeTime;

	private String elChanger;

	private String elCheckComment;

	private Integer elStatus;

	private Integer resumeId;

	// Constructors

	/** default constructor */
	public Employeelog() {
	}

	/** full constructor */
	public Employeelog(Postion postion, Integer elEmployeeId, String elName,
			Integer elAge, String elSex, Date elBirthday, Integer elNation,
			String elPhoto, Integer elDegree, String elEmail,
			String elSpecially, Integer elPolity, String elFamilyAddress,
			String elFamilyPhone, Date elEntertime, String elPhone,
			String elMobile, String elAddress, String elQq, String elPostcode,
			String elHobby, String elSkills, String elRemart,
			String elRegister, Date elRegisterTime, String elChecker,
			Date elCheckTime, Integer elCheckStatus, Date elChangeTime,
			String elChanger, String elCheckComment, Integer elStatus,
			Integer resumeId) {
		this.postion = postion;
		this.elEmployeeId = elEmployeeId;
		this.elName = elName;
		this.elAge = elAge;
		this.elSex = elSex;
		this.elBirthday = elBirthday;
		this.elNation = elNation;
		this.elPhoto = elPhoto;
		this.elDegree = elDegree;
		this.elEmail = elEmail;
		this.elSpecially = elSpecially;
		this.elPolity = elPolity;
		this.elFamilyAddress = elFamilyAddress;
		this.elFamilyPhone = elFamilyPhone;
		this.elEntertime = elEntertime;
		this.elPhone = elPhone;
		this.elMobile = elMobile;
		this.elAddress = elAddress;
		this.elQq = elQq;
		this.elPostcode = elPostcode;
		this.elHobby = elHobby;
		this.elSkills = elSkills;
		this.elRemart = elRemart;
		this.elRegister = elRegister;
		this.elRegisterTime = elRegisterTime;
		this.elChecker = elChecker;
		this.elCheckTime = elCheckTime;
		this.elCheckStatus = elCheckStatus;
		this.elChangeTime = elChangeTime;
		this.elChanger = elChanger;
		this.elCheckComment = elCheckComment;
		this.elStatus = elStatus;
		this.resumeId = resumeId;
	}

	// Property accessors

	public Integer getElId() {
		return this.elId;
	}

	public void setElId(Integer elId) {
		this.elId = elId;
	}

	public Postion getPostion() {
		return this.postion;
	}

	public void setPostion(Postion postion) {
		this.postion = postion;
	}

	public Integer getElEmployeeId() {
		return this.elEmployeeId;
	}

	public void setElEmployeeId(Integer elEmployeeId) {
		this.elEmployeeId = elEmployeeId;
	}

	public String getElName() {
		return this.elName;
	}

	public void setElName(String elName) {
		this.elName = elName;
	}

	public Integer getElAge() {
		return this.elAge;
	}

	public void setElAge(Integer elAge) {
		this.elAge = elAge;
	}

	public String getElSex() {
		return this.elSex;
	}

	public void setElSex(String elSex) {
		this.elSex = elSex;
	}

	public Date getElBirthday() {
		return this.elBirthday;
	}

	public void setElBirthday(Date elBirthday) {
		this.elBirthday = elBirthday;
	}

	public Integer getElNation() {
		return this.elNation;
	}

	public void setElNation(Integer elNation) {
		this.elNation = elNation;
	}

	public String getElPhoto() {
		return this.elPhoto;
	}

	public void setElPhoto(String elPhoto) {
		this.elPhoto = elPhoto;
	}

	public Integer getElDegree() {
		return this.elDegree;
	}

	public void setElDegree(Integer elDegree) {
		this.elDegree = elDegree;
	}

	public String getElEmail() {
		return this.elEmail;
	}

	public void setElEmail(String elEmail) {
		this.elEmail = elEmail;
	}

	public String getElSpecially() {
		return this.elSpecially;
	}

	public void setElSpecially(String elSpecially) {
		this.elSpecially = elSpecially;
	}

	public Integer getElPolity() {
		return this.elPolity;
	}

	public void setElPolity(Integer elPolity) {
		this.elPolity = elPolity;
	}

	public String getElFamilyAddress() {
		return this.elFamilyAddress;
	}

	public void setElFamilyAddress(String elFamilyAddress) {
		this.elFamilyAddress = elFamilyAddress;
	}

	public String getElFamilyPhone() {
		return this.elFamilyPhone;
	}

	public void setElFamilyPhone(String elFamilyPhone) {
		this.elFamilyPhone = elFamilyPhone;
	}

	public Date getElEntertime() {
		return this.elEntertime;
	}

	public void setElEntertime(Date elEntertime) {
		this.elEntertime = elEntertime;
	}

	public String getElPhone() {
		return this.elPhone;
	}

	public void setElPhone(String elPhone) {
		this.elPhone = elPhone;
	}

	public String getElMobile() {
		return this.elMobile;
	}

	public void setElMobile(String elMobile) {
		this.elMobile = elMobile;
	}

	public String getElAddress() {
		return this.elAddress;
	}

	public void setElAddress(String elAddress) {
		this.elAddress = elAddress;
	}

	public String getElQq() {
		return this.elQq;
	}

	public void setElQq(String elQq) {
		this.elQq = elQq;
	}

	public String getElPostcode() {
		return this.elPostcode;
	}

	public void setElPostcode(String elPostcode) {
		this.elPostcode = elPostcode;
	}

	public String getElHobby() {
		return this.elHobby;
	}

	public void setElHobby(String elHobby) {
		this.elHobby = elHobby;
	}

	public String getElSkills() {
		return this.elSkills;
	}

	public void setElSkills(String elSkills) {
		this.elSkills = elSkills;
	}

	public String getElRemart() {
		return this.elRemart;
	}

	public void setElRemart(String elRemart) {
		this.elRemart = elRemart;
	}

	public String getElRegister() {
		return this.elRegister;
	}

	public void setElRegister(String elRegister) {
		this.elRegister = elRegister;
	}

	public Date getElRegisterTime() {
		return this.elRegisterTime;
	}

	public void setElRegisterTime(Date elRegisterTime) {
		this.elRegisterTime = elRegisterTime;
	}

	public String getElChecker() {
		return this.elChecker;
	}

	public void setElChecker(String elChecker) {
		this.elChecker = elChecker;
	}

	public Date getElCheckTime() {
		return this.elCheckTime;
	}

	public void setElCheckTime(Date elCheckTime) {
		this.elCheckTime = elCheckTime;
	}

	public Integer getElCheckStatus() {
		return this.elCheckStatus;
	}

	public void setElCheckStatus(Integer elCheckStatus) {
		this.elCheckStatus = elCheckStatus;
	}

	public Date getElChangeTime() {
		return this.elChangeTime;
	}

	public void setElChangeTime(Date elChangeTime) {
		this.elChangeTime = elChangeTime;
	}

	public String getElChanger() {
		return this.elChanger;
	}

	public void setElChanger(String elChanger) {
		this.elChanger = elChanger;
	}

	public String getElCheckComment() {
		return this.elCheckComment;
	}

	public void setElCheckComment(String elCheckComment) {
		this.elCheckComment = elCheckComment;
	}

	public Integer getElStatus() {
		return this.elStatus;
	}

	public void setElStatus(Integer elStatus) {
		this.elStatus = elStatus;
	}

	public Integer getResumeId() {
		return this.resumeId;
	}

	public void setResumeId(Integer resumeId) {
		this.resumeId = resumeId;
	}

}