package net.xabc.oo.hr.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Engageexam generated by MyEclipse Persistence Tools
 */

public class Engageexam implements java.io.Serializable {

	// Fields

	private Integer eeId;

	private Examdetails examdetails;

	private Integer eePositionIssuanceId;

	private String eeRegister;

	private Date eeRegisterTime;

	private String eeLimiteTime;

	private Set examregisterdetails = new HashSet(0);

	// Constructors

	/** default constructor */
	public Engageexam() {
	}

	/** minimal constructor */
	public Engageexam(Examdetails examdetails) {
		this.examdetails = examdetails;
	}

	/** full constructor */
	public Engageexam(Examdetails examdetails, Integer eePositionIssuanceId,
			String eeRegister, Date eeRegisterTime, String eeLimiteTime,
			Set examregisterdetails) {
		this.examdetails = examdetails;
		this.eePositionIssuanceId = eePositionIssuanceId;
		this.eeRegister = eeRegister;
		this.eeRegisterTime = eeRegisterTime;
		this.eeLimiteTime = eeLimiteTime;
		this.examregisterdetails = examregisterdetails;
	}

	// Property accessors

	public Integer getEeId() {
		return this.eeId;
	}

	public void setEeId(Integer eeId) {
		this.eeId = eeId;
	}

	public Examdetails getExamdetails() {
		return this.examdetails;
	}

	public void setExamdetails(Examdetails examdetails) {
		this.examdetails = examdetails;
	}

	public Integer getEePositionIssuanceId() {
		return this.eePositionIssuanceId;
	}

	public void setEePositionIssuanceId(Integer eePositionIssuanceId) {
		this.eePositionIssuanceId = eePositionIssuanceId;
	}

	public String getEeRegister() {
		return this.eeRegister;
	}

	public void setEeRegister(String eeRegister) {
		this.eeRegister = eeRegister;
	}

	public Date getEeRegisterTime() {
		return this.eeRegisterTime;
	}

	public void setEeRegisterTime(Date eeRegisterTime) {
		this.eeRegisterTime = eeRegisterTime;
	}

	public String getEeLimiteTime() {
		return this.eeLimiteTime;
	}

	public void setEeLimiteTime(String eeLimiteTime) {
		this.eeLimiteTime = eeLimiteTime;
	}

	public Set getExamregisterdetails() {
		return this.examregisterdetails;
	}

	public void setExamregisterdetails(Set examregisterdetails) {
		this.examregisterdetails = examregisterdetails;
	}

}