package net.xabc.oo.hr.entity;

import java.util.Date;

/**
 * Examinterview generated by MyEclipse Persistence Tools
 */

public class Examinterview implements java.io.Serializable {

	// Fields

	private Integer eiId;

	private Resume resume;

	private Postion postion;

	private String eiName;

	private String eiFace;

	private Integer eiGrade;

	private String eiAbility;

	private String eiInterviewer;

	private Date eiInterviewTime;

	private String eiChecker;

	private Date eiCheckTime;

	private String eiResult;

	private String eiComment;

	private Integer eiInterviewStatue;

	private Integer eiCheckStatue;

	// Constructors

	/** default constructor */
	public Examinterview() {
	}

	/** minimal constructor */
	public Examinterview(Resume resume, Postion postion) {
		this.resume = resume;
		this.postion = postion;
	}

	/** full constructor */
	public Examinterview(Resume resume, Postion postion, String eiName,
			String eiFace, Integer eiGrade, String eiAbility,
			String eiInterviewer, Date eiInterviewTime, String eiChecker,
			Date eiCheckTime, String eiResult, String eiComment,
			Integer eiInterviewStatue, Integer eiCheckStatue) {
		this.resume = resume;
		this.postion = postion;
		this.eiName = eiName;
		this.eiFace = eiFace;
		this.eiGrade = eiGrade;
		this.eiAbility = eiAbility;
		this.eiInterviewer = eiInterviewer;
		this.eiInterviewTime = eiInterviewTime;
		this.eiChecker = eiChecker;
		this.eiCheckTime = eiCheckTime;
		this.eiResult = eiResult;
		this.eiComment = eiComment;
		this.eiInterviewStatue = eiInterviewStatue;
		this.eiCheckStatue = eiCheckStatue;
	}

	// Property accessors

	public Integer getEiId() {
		return this.eiId;
	}

	public void setEiId(Integer eiId) {
		this.eiId = eiId;
	}

	public Resume getResume() {
		return this.resume;
	}

	public void setResume(Resume resume) {
		this.resume = resume;
	}

	public Postion getPostion() {
		return this.postion;
	}

	public void setPostion(Postion postion) {
		this.postion = postion;
	}

	public String getEiName() {
		return this.eiName;
	}

	public void setEiName(String eiName) {
		this.eiName = eiName;
	}

	public String getEiFace() {
		return this.eiFace;
	}

	public void setEiFace(String eiFace) {
		this.eiFace = eiFace;
	}

	public Integer getEiGrade() {
		return this.eiGrade;
	}

	public void setEiGrade(Integer eiGrade) {
		this.eiGrade = eiGrade;
	}

	public String getEiAbility() {
		return this.eiAbility;
	}

	public void setEiAbility(String eiAbility) {
		this.eiAbility = eiAbility;
	}

	public String getEiInterviewer() {
		return this.eiInterviewer;
	}

	public void setEiInterviewer(String eiInterviewer) {
		this.eiInterviewer = eiInterviewer;
	}

	public Date getEiInterviewTime() {
		return this.eiInterviewTime;
	}

	public void setEiInterviewTime(Date eiInterviewTime) {
		this.eiInterviewTime = eiInterviewTime;
	}

	public String getEiChecker() {
		return this.eiChecker;
	}

	public void setEiChecker(String eiChecker) {
		this.eiChecker = eiChecker;
	}

	public Date getEiCheckTime() {
		return this.eiCheckTime;
	}

	public void setEiCheckTime(Date eiCheckTime) {
		this.eiCheckTime = eiCheckTime;
	}

	public String getEiResult() {
		return this.eiResult;
	}

	public void setEiResult(String eiResult) {
		this.eiResult = eiResult;
	}

	public String getEiComment() {
		return this.eiComment;
	}

	public void setEiComment(String eiComment) {
		this.eiComment = eiComment;
	}

	public Integer getEiInterviewStatue() {
		return this.eiInterviewStatue;
	}

	public void setEiInterviewStatue(Integer eiInterviewStatue) {
		this.eiInterviewStatue = eiInterviewStatue;
	}

	public Integer getEiCheckStatue() {
		return this.eiCheckStatue;
	}

	public void setEiCheckStatue(Integer eiCheckStatue) {
		this.eiCheckStatue = eiCheckStatue;
	}

}