package net.xabc.oo.hr.entity;

import java.util.HashSet;
import java.util.Set;

/**
 * Examsecondlevel generated by MyEclipse Persistence Tools
 */

public class Examsecondlevel implements java.io.Serializable {

	// Fields

	private Integer eslId;

	private String eslSecondName;

	private Integer eslDataDetailId;

	private Set examdetailses = new HashSet(0);

	private Set examsubjects = new HashSet(0);

	// Constructors

	/** default constructor */
	public Examsecondlevel() {
	}

	/** full constructor */
	public Examsecondlevel(String eslSecondName, Integer eslDataDetailId,
			Set examdetailses, Set examsubjects) {
		this.eslSecondName = eslSecondName;
		this.eslDataDetailId = eslDataDetailId;
		this.examdetailses = examdetailses;
		this.examsubjects = examsubjects;
	}

	// Property accessors

	public Integer getEslId() {
		return this.eslId;
	}

	public void setEslId(Integer eslId) {
		this.eslId = eslId;
	}

	public String getEslSecondName() {
		return this.eslSecondName;
	}

	public void setEslSecondName(String eslSecondName) {
		this.eslSecondName = eslSecondName;
	}

	public Integer getEslDataDetailId() {
		return this.eslDataDetailId;
	}

	public void setEslDataDetailId(Integer eslDataDetailId) {
		this.eslDataDetailId = eslDataDetailId;
	}

	public Set getExamdetailses() {
		return this.examdetailses;
	}

	public void setExamdetailses(Set examdetailses) {
		this.examdetailses = examdetailses;
	}

	public Set getExamsubjects() {
		return this.examsubjects;
	}

	public void setExamsubjects(Set examsubjects) {
		this.examsubjects = examsubjects;
	}

}