package net.xabc.oo.hr.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Examsubject generated by MyEclipse Persistence Tools
 */

public class Examsubject implements java.io.Serializable {

	// Fields

	private Integer subId;

	private Examsecondlevel examsecondlevel;

	private Branch branch;

	private String subContent;

	private String subAnswer1;

	private String subAnswer2;

	private String subAnswer3;

	private String subAnswer4;

	private String subCorrectAuswer;

	private String subRegister;

	private Date subRegisterTime;

	private String subChanger;

	private Date subChangerTime;

	private Integer subState;

	private Set examregisterdetails = new HashSet(0);

	// Constructors

	/** default constructor */
	public Examsubject() {
	}

	/** minimal constructor */
	public Examsubject(Examsecondlevel examsecondlevel, Branch branch) {
		this.examsecondlevel = examsecondlevel;
		this.branch = branch;
	}

	/** full constructor */
	public Examsubject(Examsecondlevel examsecondlevel, Branch branch,
			String subContent, String subAnswer1, String subAnswer2,
			String subAnswer3, String subAnswer4, String subCorrectAuswer,
			String subRegister, Date subRegisterTime, String subChanger,
			Date subChangerTime, Integer subState, Set examregisterdetails) {
		this.examsecondlevel = examsecondlevel;
		this.branch = branch;
		this.subContent = subContent;
		this.subAnswer1 = subAnswer1;
		this.subAnswer2 = subAnswer2;
		this.subAnswer3 = subAnswer3;
		this.subAnswer4 = subAnswer4;
		this.subCorrectAuswer = subCorrectAuswer;
		this.subRegister = subRegister;
		this.subRegisterTime = subRegisterTime;
		this.subChanger = subChanger;
		this.subChangerTime = subChangerTime;
		this.subState = subState;
		this.examregisterdetails = examregisterdetails;
	}

	// Property accessors

	public Integer getSubId() {
		return this.subId;
	}

	public void setSubId(Integer subId) {
		this.subId = subId;
	}

	public Examsecondlevel getExamsecondlevel() {
		return this.examsecondlevel;
	}

	public void setExamsecondlevel(Examsecondlevel examsecondlevel) {
		this.examsecondlevel = examsecondlevel;
	}

	public Branch getBranch() {
		return this.branch;
	}

	public void setBranch(Branch branch) {
		this.branch = branch;
	}

	public String getSubContent() {
		return this.subContent;
	}

	public void setSubContent(String subContent) {
		this.subContent = subContent;
	}

	public String getSubAnswer1() {
		return this.subAnswer1;
	}

	public void setSubAnswer1(String subAnswer1) {
		this.subAnswer1 = subAnswer1;
	}

	public String getSubAnswer2() {
		return this.subAnswer2;
	}

	public void setSubAnswer2(String subAnswer2) {
		this.subAnswer2 = subAnswer2;
	}

	public String getSubAnswer3() {
		return this.subAnswer3;
	}

	public void setSubAnswer3(String subAnswer3) {
		this.subAnswer3 = subAnswer3;
	}

	public String getSubAnswer4() {
		return this.subAnswer4;
	}

	public void setSubAnswer4(String subAnswer4) {
		this.subAnswer4 = subAnswer4;
	}

	public String getSubCorrectAuswer() {
		return this.subCorrectAuswer;
	}

	public void setSubCorrectAuswer(String subCorrectAuswer) {
		this.subCorrectAuswer = subCorrectAuswer;
	}

	public String getSubRegister() {
		return this.subRegister;
	}

	public void setSubRegister(String subRegister) {
		this.subRegister = subRegister;
	}

	public Date getSubRegisterTime() {
		return this.subRegisterTime;
	}

	public void setSubRegisterTime(Date subRegisterTime) {
		this.subRegisterTime = subRegisterTime;
	}

	public String getSubChanger() {
		return this.subChanger;
	}

	public void setSubChanger(String subChanger) {
		this.subChanger = subChanger;
	}

	public Date getSubChangerTime() {
		return this.subChangerTime;
	}

	public void setSubChangerTime(Date subChangerTime) {
		this.subChangerTime = subChangerTime;
	}

	public Integer getSubState() {
		return this.subState;
	}

	public void setSubState(Integer subState) {
		this.subState = subState;
	}

	public Set getExamregisterdetails() {
		return this.examregisterdetails;
	}

	public void setExamregisterdetails(Set examregisterdetails) {
		this.examregisterdetails = examregisterdetails;
	}

}