package net.xabc.oo.hr.entity;

/**
 * Examregisterdetail generated by MyEclipse Persistence Tools
 */

public class Examregisterdetail implements java.io.Serializable {

	// Fields

	private Integer erdId;

	private Engageexam engageexam;

	private Examsubject examsubject;

	// Constructors

	/** default constructor */
	public Examregisterdetail() {
	}

	/** full constructor */
	public Examregisterdetail(Engageexam engageexam, Examsubject examsubject) {
		this.engageexam = engageexam;
		this.examsubject = examsubject;
	}

	// Property accessors

	public Integer getErdId() {
		return this.erdId;
	}

	public void setErdId(Integer erdId) {
		this.erdId = erdId;
	}

	public Engageexam getEngageexam() {
		return this.engageexam;
	}

	public void setEngageexam(Engageexam engageexam) {
		this.engageexam = engageexam;
	}

	public Examsubject getExamsubject() {
		return this.examsubject;
	}

	public void setExamsubject(Examsubject examsubject) {
		this.examsubject = examsubject;
	}

}