package net.xabc.oo.hr.entity;

import java.util.Date;

/**
 * Positionissuance generated by MyEclipse Persistence Tools
 */

public class Positionissuance implements java.io.Serializable {

	// Fields

	private Integer positionIssuanceId;

	private Postion postion;

	private Integer positionIssuanceRequireNum;

	private Date positionIssuanceEndTime;

	private String positionIssuanceRegister;

	private Date positionIssuanceResiterTime;

	private String positionIssuanceChange;

	private Date positionIssuanceChangeTime;

	private String positionIssuanceDescription;

	private String positionIssuanceRequire;

	// Constructors

	/** default constructor */
	public Positionissuance() {
	}

	/** minimal constructor */
	public Positionissuance(Postion postion) {
		this.postion = postion;
	}

	/** full constructor */
	public Positionissuance(Postion postion,
			Integer positionIssuanceRequireNum, Date positionIssuanceEndTime,
			String positionIssuanceRegister, Date positionIssuanceResiterTime,
			String positionIssuanceChange, Date positionIssuanceChangeTime,
			String positionIssuanceDescription, String positionIssuanceRequire) {
		this.postion = postion;
		this.positionIssuanceRequireNum = positionIssuanceRequireNum;
		this.positionIssuanceEndTime = positionIssuanceEndTime;
		this.positionIssuanceRegister = positionIssuanceRegister;
		this.positionIssuanceResiterTime = positionIssuanceResiterTime;
		this.positionIssuanceChange = positionIssuanceChange;
		this.positionIssuanceChangeTime = positionIssuanceChangeTime;
		this.positionIssuanceDescription = positionIssuanceDescription;
		this.positionIssuanceRequire = positionIssuanceRequire;
	}

	// Property accessors

	public Integer getPositionIssuanceId() {
		return this.positionIssuanceId;
	}

	public void setPositionIssuanceId(Integer positionIssuanceId) {
		this.positionIssuanceId = positionIssuanceId;
	}

	public Postion getPostion() {
		return this.postion;
	}

	public void setPostion(Postion postion) {
		this.postion = postion;
	}

	public Integer getPositionIssuanceRequireNum() {
		return this.positionIssuanceRequireNum;
	}

	public void setPositionIssuanceRequireNum(Integer positionIssuanceRequireNum) {
		this.positionIssuanceRequireNum = positionIssuanceRequireNum;
	}

	public Date getPositionIssuanceEndTime() {
		return this.positionIssuanceEndTime;
	}

	public void setPositionIssuanceEndTime(Date positionIssuanceEndTime) {
		this.positionIssuanceEndTime = positionIssuanceEndTime;
	}

	public String getPositionIssuanceRegister() {
		return this.positionIssuanceRegister;
	}

	public void setPositionIssuanceRegister(String positionIssuanceRegister) {
		this.positionIssuanceRegister = positionIssuanceRegister;
	}

	public Date getPositionIssuanceResiterTime() {
		return this.positionIssuanceResiterTime;
	}

	public void setPositionIssuanceResiterTime(Date positionIssuanceResiterTime) {
		this.positionIssuanceResiterTime = positionIssuanceResiterTime;
	}

	public String getPositionIssuanceChange() {
		return this.positionIssuanceChange;
	}

	public void setPositionIssuanceChange(String positionIssuanceChange) {
		this.positionIssuanceChange = positionIssuanceChange;
	}

	public Date getPositionIssuanceChangeTime() {
		return this.positionIssuanceChangeTime;
	}

	public void setPositionIssuanceChangeTime(Date positionIssuanceChangeTime) {
		this.positionIssuanceChangeTime = positionIssuanceChangeTime;
	}

	public String getPositionIssuanceDescription() {
		return this.positionIssuanceDescription;
	}

	public void setPositionIssuanceDescription(
			String positionIssuanceDescription) {
		this.positionIssuanceDescription = positionIssuanceDescription;
	}

	public String getPositionIssuanceRequire() {
		return this.positionIssuanceRequire;
	}

	public void setPositionIssuanceRequire(String positionIssuanceRequire) {
		this.positionIssuanceRequire = positionIssuanceRequire;
	}

}