package net.xabc.oo.hr.entity;

import java.util.HashSet;
import java.util.Set;

/**
 * Postion generated by MyEclipse Persistence Tools
 */

public class Postion implements java.io.Serializable {

	// Fields

	private Integer positionId;

	private Branch branch;

	private String positionName;

	private Set positionissuances = new HashSet(0);

	private Set employees = new HashSet(0);

	private Set userses = new HashSet(0);

	private Set employeelogs = new HashSet(0);

	private Set examinterviews = new HashSet(0);

	private Set salarystandards = new HashSet(0);

	// Constructors

	/** default constructor */
	public Postion() {
	}

	/** minimal constructor */
	public Postion(Branch branch, String positionName) {
		this.branch = branch;
		this.positionName = positionName;
	}

	/** full constructor */
	public Postion(Branch branch, String positionName, Set positionissuances,
			Set employees, Set userses, Set employeelogs, Set examinterviews,
			Set salarystandards) {
		this.branch = branch;
		this.positionName = positionName;
		this.positionissuances = positionissuances;
		this.employees = employees;
		this.userses = userses;
		this.employeelogs = employeelogs;
		this.examinterviews = examinterviews;
		this.salarystandards = salarystandards;
	}

	// Property accessors

	public Integer getPositionId() {
		return this.positionId;
	}

	public void setPositionId(Integer positionId) {
		this.positionId = positionId;
	}

	public Branch getBranch() {
		return this.branch;
	}

	public void setBranch(Branch branch) {
		this.branch = branch;
	}

	public String getPositionName() {
		return this.positionName;
	}

	public void setPositionName(String positionName) {
		this.positionName = positionName;
	}

	public Set getPositionissuances() {
		return this.positionissuances;
	}

	public void setPositionissuances(Set positionissuances) {
		this.positionissuances = positionissuances;
	}

	public Set getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set employees) {
		this.employees = employees;
	}

	public Set getUserses() {
		return this.userses;
	}

	public void setUserses(Set userses) {
		this.userses = userses;
	}

	public Set getEmployeelogs() {
		return this.employeelogs;
	}

	public void setEmployeelogs(Set employeelogs) {
		this.employeelogs = employeelogs;
	}

	public Set getExaminterviews() {
		return this.examinterviews;
	}

	public void setExaminterviews(Set examinterviews) {
		this.examinterviews = examinterviews;
	}

	public Set getSalarystandards() {
		return this.salarystandards;
	}

	public void setSalarystandards(Set salarystandards) {
		this.salarystandards = salarystandards;
	}

}