package net.xabc.oo.hr.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Resume generated by MyEclipse Persistence Tools
 */

public class Resume implements java.io.Serializable {

	// Fields

	private Integer resumeId;

	private String personName;

	private Date resumeTime;

	private String resumeSex;

	private Integer resumeAge;

	private Date resumeBirthday;

	private Integer resumeDegree;

	private Integer resumePositionId;

	private String resumeGraduate;

	private Integer resumePolity;

	private String resumePhoto;

	private String resumeIdCard;

	private Integer resumeNation;

	private String resumeSpeciality;

	private String resumeHistory;

	private String resumeBirthPlace;

	private String resumeRequire;

	private String resumePhone;

	private String resumePostcode;

	private String resumeEmail;

	private String resumeFamilyPhone;

	private String resumeHobby;

	private String resumeSkill;

	private Integer resumeInterviewstatus;

	private Integer resumeStatus;

	private String resumeRegister;

	private Date resumeRegisterTime;

	private String resumeChecker;

	private Date resumeCheckTime;

	private Integer resumeCheckStatus;

	private String resumeCheckCommit;

	private Set examinterviews = new HashSet(0);

	// Constructors

	/** default constructor */
	public Resume() {
	}

	/** full constructor */
	public Resume(String personName, Date resumeTime, String resumeSex,
			Integer resumeAge, Date resumeBirthday, Integer resumeDegree,
			Integer resumePositionId, String resumeGraduate,
			Integer resumePolity, String resumePhoto, String resumeIdCard,
			Integer resumeNation, String resumeSpeciality,
			String resumeHistory, String resumeBirthPlace,
			String resumeRequire, String resumePhone, String resumePostcode,
			String resumeEmail, String resumeFamilyPhone, String resumeHobby,
			String resumeSkill, Integer resumeInterviewstatus,
			Integer resumeStatus, String resumeRegister,
			Date resumeRegisterTime, String resumeChecker,
			Date resumeCheckTime, Integer resumeCheckStatus,
			String resumeCheckCommit, Set examinterviews) {
		this.personName = personName;
		this.resumeTime = resumeTime;
		this.resumeSex = resumeSex;
		this.resumeAge = resumeAge;
		this.resumeBirthday = resumeBirthday;
		this.resumeDegree = resumeDegree;
		this.resumePositionId = resumePositionId;
		this.resumeGraduate = resumeGraduate;
		this.resumePolity = resumePolity;
		this.resumePhoto = resumePhoto;
		this.resumeIdCard = resumeIdCard;
		this.resumeNation = resumeNation;
		this.resumeSpeciality = resumeSpeciality;
		this.resumeHistory = resumeHistory;
		this.resumeBirthPlace = resumeBirthPlace;
		this.resumeRequire = resumeRequire;
		this.resumePhone = resumePhone;
		this.resumePostcode = resumePostcode;
		this.resumeEmail = resumeEmail;
		this.resumeFamilyPhone = resumeFamilyPhone;
		this.resumeHobby = resumeHobby;
		this.resumeSkill = resumeSkill;
		this.resumeInterviewstatus = resumeInterviewstatus;
		this.resumeStatus = resumeStatus;
		this.resumeRegister = resumeRegister;
		this.resumeRegisterTime = resumeRegisterTime;
		this.resumeChecker = resumeChecker;
		this.resumeCheckTime = resumeCheckTime;
		this.resumeCheckStatus = resumeCheckStatus;
		this.resumeCheckCommit = resumeCheckCommit;
		this.examinterviews = examinterviews;
	}

	// Property accessors

	public Integer getResumeId() {
		return this.resumeId;
	}

	public void setResumeId(Integer resumeId) {
		this.resumeId = resumeId;
	}

	public String getPersonName() {
		return this.personName;
	}

	public void setPersonName(String personName) {
		this.personName = personName;
	}

	public Date getResumeTime() {
		return this.resumeTime;
	}

	public void setResumeTime(Date resumeTime) {
		this.resumeTime = resumeTime;
	}

	public String getResumeSex() {
		return this.resumeSex;
	}

	public void setResumeSex(String resumeSex) {
		this.resumeSex = resumeSex;
	}

	public Integer getResumeAge() {
		return this.resumeAge;
	}

	public void setResumeAge(Integer resumeAge) {
		this.resumeAge = resumeAge;
	}

	public Date getResumeBirthday() {
		return this.resumeBirthday;
	}

	public void setResumeBirthday(Date resumeBirthday) {
		this.resumeBirthday = resumeBirthday;
	}

	public Integer getResumeDegree() {
		return this.resumeDegree;
	}

	public void setResumeDegree(Integer resumeDegree) {
		this.resumeDegree = resumeDegree;
	}

	public Integer getResumePositionId() {
		return this.resumePositionId;
	}

	public void setResumePositionId(Integer resumePositionId) {
		this.resumePositionId = resumePositionId;
	}

	public String getResumeGraduate() {
		return this.resumeGraduate;
	}

	public void setResumeGraduate(String resumeGraduate) {
		this.resumeGraduate = resumeGraduate;
	}

	public Integer getResumePolity() {
		return this.resumePolity;
	}

	public void setResumePolity(Integer resumePolity) {
		this.resumePolity = resumePolity;
	}

	public String getResumePhoto() {
		return this.resumePhoto;
	}

	public void setResumePhoto(String resumePhoto) {
		this.resumePhoto = resumePhoto;
	}

	public String getResumeIdCard() {
		return this.resumeIdCard;
	}

	public void setResumeIdCard(String resumeIdCard) {
		this.resumeIdCard = resumeIdCard;
	}

	public Integer getResumeNation() {
		return this.resumeNation;
	}

	public void setResumeNation(Integer resumeNation) {
		this.resumeNation = resumeNation;
	}

	public String getResumeSpeciality() {
		return this.resumeSpeciality;
	}

	public void setResumeSpeciality(String resumeSpeciality) {
		this.resumeSpeciality = resumeSpeciality;
	}

	public String getResumeHistory() {
		return this.resumeHistory;
	}

	public void setResumeHistory(String resumeHistory) {
		this.resumeHistory = resumeHistory;
	}

	public String getResumeBirthPlace() {
		return this.resumeBirthPlace;
	}

	public void setResumeBirthPlace(String resumeBirthPlace) {
		this.resumeBirthPlace = resumeBirthPlace;
	}

	public String getResumeRequire() {
		return this.resumeRequire;
	}

	public void setResumeRequire(String resumeRequire) {
		this.resumeRequire = resumeRequire;
	}

	public String getResumePhone() {
		return this.resumePhone;
	}

	public void setResumePhone(String resumePhone) {
		this.resumePhone = resumePhone;
	}

	public String getResumePostcode() {
		return this.resumePostcode;
	}

	public void setResumePostcode(String resumePostcode) {
		this.resumePostcode = resumePostcode;
	}

	public String getResumeEmail() {
		return this.resumeEmail;
	}

	public void setResumeEmail(String resumeEmail) {
		this.resumeEmail = resumeEmail;
	}

	public String getResumeFamilyPhone() {
		return this.resumeFamilyPhone;
	}

	public void setResumeFamilyPhone(String resumeFamilyPhone) {
		this.resumeFamilyPhone = resumeFamilyPhone;
	}

	public String getResumeHobby() {
		return this.resumeHobby;
	}

	public void setResumeHobby(String resumeHobby) {
		this.resumeHobby = resumeHobby;
	}

	public String getResumeSkill() {
		return this.resumeSkill;
	}

	public void setResumeSkill(String resumeSkill) {
		this.resumeSkill = resumeSkill;
	}

	public Integer getResumeInterviewstatus() {
		return this.resumeInterviewstatus;
	}

	public void setResumeInterviewstatus(Integer resumeInterviewstatus) {
		this.resumeInterviewstatus = resumeInterviewstatus;
	}

	public Integer getResumeStatus() {
		return this.resumeStatus;
	}

	public void setResumeStatus(Integer resumeStatus) {
		this.resumeStatus = resumeStatus;
	}

	public String getResumeRegister() {
		return this.resumeRegister;
	}

	public void setResumeRegister(String resumeRegister) {
		this.resumeRegister = resumeRegister;
	}

	public Date getResumeRegisterTime() {
		return this.resumeRegisterTime;
	}

	public void setResumeRegisterTime(Date resumeRegisterTime) {
		this.resumeRegisterTime = resumeRegisterTime;
	}

	public String getResumeChecker() {
		return this.resumeChecker;
	}

	public void setResumeChecker(String resumeChecker) {
		this.resumeChecker = resumeChecker;
	}

	public Date getResumeCheckTime() {
		return this.resumeCheckTime;
	}

	public void setResumeCheckTime(Date resumeCheckTime) {
		this.resumeCheckTime = resumeCheckTime;
	}

	public Integer getResumeCheckStatus() {
		return this.resumeCheckStatus;
	}

	public void setResumeCheckStatus(Integer resumeCheckStatus) {
		this.resumeCheckStatus = resumeCheckStatus;
	}

	public String getResumeCheckCommit() {
		return this.resumeCheckCommit;
	}

	public void setResumeCheckCommit(String resumeCheckCommit) {
		this.resumeCheckCommit = resumeCheckCommit;
	}

	public Set getExaminterviews() {
		return this.examinterviews;
	}

	public void setExaminterviews(Set examinterviews) {
		this.examinterviews = examinterviews;
	}

}