package net.xabc.oo.hr.entity;

import java.util.HashSet;
import java.util.Set;

/**
 * Rights generated by MyEclipse Persistence Tools
 */

public class Rights implements java.io.Serializable {

	// Fields

	private String rightsCode;

	private String rightsParentCode;

	private String rightsName;

	private String rightsUrl;

	private Set rolerightses = new HashSet(0);

	// Constructors

	/** default constructor */
	public Rights() {
	}

	/** minimal constructor */
	public Rights(String rightsCode) {
		this.rightsCode = rightsCode;
	}

	/** full constructor */
	public Rights(String rightsCode, String rightsParentCode,
			String rightsName, String rightsUrl, Set rolerightses) {
		this.rightsCode = rightsCode;
		this.rightsParentCode = rightsParentCode;
		this.rightsName = rightsName;
		this.rightsUrl = rightsUrl;
		this.rolerightses = rolerightses;
	}

	// Property accessors

	public String getRightsCode() {
		return this.rightsCode;
	}

	public void setRightsCode(String rightsCode) {
		this.rightsCode = rightsCode;
	}

	public String getRightsParentCode() {
		return this.rightsParentCode;
	}

	public void setRightsParentCode(String rightsParentCode) {
		this.rightsParentCode = rightsParentCode;
	}

	public String getRightsName() {
		return this.rightsName;
	}

	public void setRightsName(String rightsName) {
		this.rightsName = rightsName;
	}

	public String getRightsUrl() {
		return this.rightsUrl;
	}

	public void setRightsUrl(String rightsUrl) {
		this.rightsUrl = rightsUrl;
	}

	public Set getRolerightses() {
		return this.rolerightses;
	}

	public void setRolerightses(Set rolerightses) {
		this.rolerightses = rolerightses;
	}

}