package net.xabc.oo.hr.entity;

/**
 * Rolerights generated by MyEclipse Persistence Tools
 */

public class Rolerights implements java.io.Serializable {

	// Fields

	private Integer roleRightsId;

	private Rights rights;

	private Role role;

	// Constructors

	/** default constructor */
	public Rolerights() {
	}

	/** full constructor */
	public Rolerights(Rights rights, Role role) {
		this.rights = rights;
		this.role = role;
	}

	// Property accessors

	public Integer getRoleRightsId() {
		return this.roleRightsId;
	}

	public void setRoleRightsId(Integer roleRightsId) {
		this.roleRightsId = roleRightsId;
	}

	public Rights getRights() {
		return this.rights;
	}

	public void setRights(Rights rights) {
		this.rights = rights;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

}