package net.xabc.oo.hr.entity;

import java.util.Date;

/**
 * Salarygrant generated by MyEclipse Persistence Tools
 */

public class Salarygrant implements java.io.Serializable {

	// Fields

	private Integer sgId;

	private Employee employee;

	private Salarystandard salarystandard;

	private Long sgFactMoney;

	private Long sgDeductMoney;

	private Long sgTotalMoney;

	private String sgRegister;

	private Date sgRegisterTime;

	private String sgChecker;

	private Date sgCheckTime;

	private Integer sgCheckStatus;

	private String sgCommit;

	// Constructors

	/** default constructor */
	public Salarygrant() {
	}

	/** minimal constructor */
	public Salarygrant(Employee employee, Salarystandard salarystandard) {
		this.employee = employee;
		this.salarystandard = salarystandard;
	}

	/** full constructor */
	public Salarygrant(Employee employee, Salarystandard salarystandard,
			Long sgFactMoney, Long sgDeductMoney, Long sgTotalMoney,
			String sgRegister, Date sgRegisterTime, String sgChecker,
			Date sgCheckTime, Integer sgCheckStatus, String sgCommit) {
		this.employee = employee;
		this.salarystandard = salarystandard;
		this.sgFactMoney = sgFactMoney;
		this.sgDeductMoney = sgDeductMoney;
		this.sgTotalMoney = sgTotalMoney;
		this.sgRegister = sgRegister;
		this.sgRegisterTime = sgRegisterTime;
		this.sgChecker = sgChecker;
		this.sgCheckTime = sgCheckTime;
		this.sgCheckStatus = sgCheckStatus;
		this.sgCommit = sgCommit;
	}

	// Property accessors

	public Integer getSgId() {
		return this.sgId;
	}

	public void setSgId(Integer sgId) {
		this.sgId = sgId;
	}

	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public Salarystandard getSalarystandard() {
		return this.salarystandard;
	}

	public void setSalarystandard(Salarystandard salarystandard) {
		this.salarystandard = salarystandard;
	}

	public Long getSgFactMoney() {
		return this.sgFactMoney;
	}

	public void setSgFactMoney(Long sgFactMoney) {
		this.sgFactMoney = sgFactMoney;
	}

	public Long getSgDeductMoney() {
		return this.sgDeductMoney;
	}

	public void setSgDeductMoney(Long sgDeductMoney) {
		this.sgDeductMoney = sgDeductMoney;
	}

	public Long getSgTotalMoney() {
		return this.sgTotalMoney;
	}

	public void setSgTotalMoney(Long sgTotalMoney) {
		this.sgTotalMoney = sgTotalMoney;
	}

	public String getSgRegister() {
		return this.sgRegister;
	}

	public void setSgRegister(String sgRegister) {
		this.sgRegister = sgRegister;
	}

	public Date getSgRegisterTime() {
		return this.sgRegisterTime;
	}

	public void setSgRegisterTime(Date sgRegisterTime) {
		this.sgRegisterTime = sgRegisterTime;
	}

	public String getSgChecker() {
		return this.sgChecker;
	}

	public void setSgChecker(String sgChecker) {
		this.sgChecker = sgChecker;
	}

	public Date getSgCheckTime() {
		return this.sgCheckTime;
	}

	public void setSgCheckTime(Date sgCheckTime) {
		this.sgCheckTime = sgCheckTime;
	}

	public Integer getSgCheckStatus() {
		return this.sgCheckStatus;
	}

	public void setSgCheckStatus(Integer sgCheckStatus) {
		this.sgCheckStatus = sgCheckStatus;
	}

	public String getSgCommit() {
		return this.sgCommit;
	}

	public void setSgCommit(String sgCommit) {
		this.sgCommit = sgCommit;
	}

}