package net.xabc.oo.hr.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Salarystandard generated by MyEclipse Persistence Tools
 */

public class Salarystandard implements java.io.Serializable {

	// Fields

	private Integer ssId;

	private Postion postion;

	private Long basicMoney;

	private Long contact;

	private Long floatWage;

	private Long trafficSubsidy;

	private Long lunchSubsidy;

	private String ssDesigner;

	private String ssRegister;

	private Date ssRegisterTime;

	private String ssChecker;

	private Date ssCheckerTime;

	private String ssChange;

	private Date ssChangeTime;

	private Long ssSalary;

	private Integer ssCheckStatus;

	private String ssComment;

	private Set salarygrants = new HashSet(0);

	// Constructors

	/** default constructor */
	public Salarystandard() {
	}

	/** full constructor */
	public Salarystandard(Postion postion, Long basicMoney, Long contact,
			Long floatWage, Long trafficSubsidy, Long lunchSubsidy,
			String ssDesigner, String ssRegister, Date ssRegisterTime,
			String ssChecker, Date ssCheckerTime, String ssChange,
			Date ssChangeTime, Long ssSalary, Integer ssCheckStatus,
			String ssComment, Set salarygrants) {
		this.postion = postion;
		this.basicMoney = basicMoney;
		this.contact = contact;
		this.floatWage = floatWage;
		this.trafficSubsidy = trafficSubsidy;
		this.lunchSubsidy = lunchSubsidy;
		this.ssDesigner = ssDesigner;
		this.ssRegister = ssRegister;
		this.ssRegisterTime = ssRegisterTime;
		this.ssChecker = ssChecker;
		this.ssCheckerTime = ssCheckerTime;
		this.ssChange = ssChange;
		this.ssChangeTime = ssChangeTime;
		this.ssSalary = ssSalary;
		this.ssCheckStatus = ssCheckStatus;
		this.ssComment = ssComment;
		this.salarygrants = salarygrants;
	}

	// Property accessors

	public Integer getSsId() {
		return this.ssId;
	}

	public void setSsId(Integer ssId) {
		this.ssId = ssId;
	}

	public Postion getPostion() {
		return this.postion;
	}

	public void setPostion(Postion postion) {
		this.postion = postion;
	}

	public Long getBasicMoney() {
		return this.basicMoney;
	}

	public void setBasicMoney(Long basicMoney) {
		this.basicMoney = basicMoney;
	}

	public Long getContact() {
		return this.contact;
	}

	public void setContact(Long contact) {
		this.contact = contact;
	}

	public Long getFloatWage() {
		return this.floatWage;
	}

	public void setFloatWage(Long floatWage) {
		this.floatWage = floatWage;
	}

	public Long getTrafficSubsidy() {
		return this.trafficSubsidy;
	}

	public void setTrafficSubsidy(Long trafficSubsidy) {
		this.trafficSubsidy = trafficSubsidy;
	}

	public Long getLunchSubsidy() {
		return this.lunchSubsidy;
	}

	public void setLunchSubsidy(Long lunchSubsidy) {
		this.lunchSubsidy = lunchSubsidy;
	}

	public String getSsDesigner() {
		return this.ssDesigner;
	}

	public void setSsDesigner(String ssDesigner) {
		this.ssDesigner = ssDesigner;
	}

	public String getSsRegister() {
		return this.ssRegister;
	}

	public void setSsRegister(String ssRegister) {
		this.ssRegister = ssRegister;
	}

	public Date getSsRegisterTime() {
		return this.ssRegisterTime;
	}

	public void setSsRegisterTime(Date ssRegisterTime) {
		this.ssRegisterTime = ssRegisterTime;
	}

	public String getSsChecker() {
		return this.ssChecker;
	}

	public void setSsChecker(String ssChecker) {
		this.ssChecker = ssChecker;
	}

	public Date getSsCheckerTime() {
		return this.ssCheckerTime;
	}

	public void setSsCheckerTime(Date ssCheckerTime) {
		this.ssCheckerTime = ssCheckerTime;
	}

	public String getSsChange() {
		return this.ssChange;
	}

	public void setSsChange(String ssChange) {
		this.ssChange = ssChange;
	}

	public Date getSsChangeTime() {
		return this.ssChangeTime;
	}

	public void setSsChangeTime(Date ssChangeTime) {
		this.ssChangeTime = ssChangeTime;
	}

	public Long getSsSalary() {
		return this.ssSalary;
	}

	public void setSsSalary(Long ssSalary) {
		this.ssSalary = ssSalary;
	}

	public Integer getSsCheckStatus() {
		return this.ssCheckStatus;
	}

	public void setSsCheckStatus(Integer ssCheckStatus) {
		this.ssCheckStatus = ssCheckStatus;
	}

	public String getSsComment() {
		return this.ssComment;
	}

	public void setSsComment(String ssComment) {
		this.ssComment = ssComment;
	}

	public Set getSalarygrants() {
		return this.salarygrants;
	}

	public void setSalarygrants(Set salarygrants) {
		this.salarygrants = salarygrants;
	}

}