package net.xabc.oo.hr.entity;

/**
 * Users generated by MyEclipse Persistence Tools
 */

public class Users implements java.io.Serializable {

	// Fields

	private Integer userId;

	private Employee employee;

	private Role role;

	private Postion postion;

	private String userName;

	private String userPassword;

	private Integer userState;

	// Constructors

	/** default constructor */
	public Users() {
	}

	/** full constructor */
	public Users(Employee employee, Role role, Postion postion,
			String userName, String userPassword, Integer userState) {
		this.employee = employee;
		this.role = role;
		this.postion = postion;
		this.userName = userName;
		this.userPassword = userPassword;
		this.userState = userState;
	}

	// Property accessors

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public Postion getPostion() {
		return this.postion;
	}

	public void setPostion(Postion postion) {
		this.postion = postion;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	public Integer getUserState() {
		return this.userState;
	}

	public void setUserState(Integer userState) {
		this.userState = userState;
	}

}